# Site settings
title: "{\"title\": \"Who let the dogs out\"}"
email: info@hakanu.net
description: > # this means to ignore newlines until "baseurl:"
  Some random hacker writes random stuff on software development,
  frameworks, entrepreneurship, geeky stuff, startups, python, serverless, web development, big data,
  machine learning, data mining, parallel processing, GPUs etc.
todo: Write at least one blog post per week.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hakanu.net" # the base hostname & protocol for your site
twitter_username: hakanu_
github_username:  hakanu
instagram_username: hakanu_

# Build settings
markdown: kramdown
#markdown: redcarpet
permalink: pretty
paginate: 10
paginate_path: "/page/:num/"
highlighter: rouge #pygments
kramdown:
  input: GFM
  hard_wrap: false
#redcarpet:
#  extensions: ["autolink", "fenced_code_blocks"]
gems:
  - jekyll-sitemap
